// Copyright 2026 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

//go:build ignore

// dump_program is a small standalone helper that prints both the syzlang
// AST view and the wire-format hex of a single edk2 program generated by
// the syzkaller prog package. Useful for documentation and debugging.
//
// Run from a syzkaller checkout with:
//   ./tools/syz-env go run tools/syz-edk2-fuzz/dump_program.go [seed]

package main

import (
	"encoding/hex"
	"fmt"
	"math/rand"
	"os"
	"strconv"

	"github.com/google/syzkaller/prog"
	_ "github.com/google/syzkaller/sys"
)

func main() {
	seed := int64(42)
	if len(os.Args) > 1 {
		s, err := strconv.ParseInt(os.Args[1], 10, 64)
		if err == nil {
			seed = s
		}
	}
	t, err := prog.GetTarget("edk2", "amd64")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	ct := t.DefaultChoiceTable()
	rs := rand.NewSource(seed)
	p := t.Generate(rs, 1, ct)

	fmt.Println("================  syzlang serialized program ================")
	fmt.Println(string(p.Serialize()))

	fmt.Println("================  AST walk of the *prog.Prog tree ================")
	for _, c := range p.Calls {
		fmt.Printf("call: %s\n", c.Meta.Name)
		walk(c.Args, 1)
	}

	fmt.Println("================  reproduced wire-format bytes ================")
	// Re-use the same emitter as the live fuzzer.
	// The walker is in grammar.go in the same package; here we duplicate
	// only the parts we need so this file stays standalone.
	for _, c := range p.Calls {
		if c.Meta.Name != "syz_edk2_run_program" {
			continue
		}
		ptr := c.Args[0].(*prog.PointerArg)
		grp := ptr.Res.(*prog.GroupArg)
		callsArr := grp.Inner[2].(*prog.GroupArg)
		off := 0
		for _, item := range callsArr.Inner {
			u, ok := item.(*prog.UnionArg)
			if !ok {
				continue
			}
			api := u.Option.(*prog.GroupArg)
			callID := uint32(api.Inner[0].(*prog.ConstArg).Val)
			payBytes := serialize(api.Inner[2])
			recBytes := append([]byte{}, leU32(callID)...)
			recBytes = append(recBytes, leU32(uint32(8+len(payBytes)))...)
			recBytes = append(recBytes, payBytes...)
			fmt.Printf("[off=0x%04x] call_id=%d size=%d\n", off, callID, 8+len(payBytes))
			fmt.Printf("            %s\n", hex.EncodeToString(recBytes))
			off += len(recBytes)
		}
	}
}

func walk(args []prog.Arg, depth int) {
	for _, a := range args {
		switch x := a.(type) {
		case *prog.ConstArg:
			fmt.Printf("%sConstArg name=%s val=%d size=%d\n", indent(depth), name(a), x.Val, x.Size())
		case *prog.PointerArg:
			fmt.Printf("%sPointerArg name=%s res=%T\n", indent(depth), name(a), x.Res)
			if x.Res != nil {
				walk([]prog.Arg{x.Res}, depth+1)
			}
		case *prog.GroupArg:
			fmt.Printf("%sGroupArg name=%s len=%d\n", indent(depth), name(a), len(x.Inner))
			walk(x.Inner, depth+1)
		case *prog.UnionArg:
			fmt.Printf("%sUnionArg name=%s opt=%s\n", indent(depth), name(a), name(x.Option))
			walk([]prog.Arg{x.Option}, depth+1)
		case *prog.DataArg:
			fmt.Printf("%sDataArg name=%s len=%d\n", indent(depth), name(a), len(x.Data()))
		case *prog.ResultArg:
			fmt.Printf("%sResultArg name=%s\n", indent(depth), name(a))
		}
	}
}

func name(a prog.Arg) string {
	if a == nil {
		return "<nil>"
	}
	t := a.Type()
	if t == nil {
		return "<no-type>"
	}
	return t.Name()
}

func indent(d int) string {
	s := ""
	for i := 0; i < d; i++ {
		s += "  "
	}
	return s
}

func leU32(v uint32) []byte {
	return []byte{byte(v), byte(v >> 8), byte(v >> 16), byte(v >> 24)}
}

func serialize(a prog.Arg) []byte {
	var out []byte
	switch x := a.(type) {
	case *prog.ConstArg:
		v, _ := x.Value()
		for i := uint64(0); i < uint64(x.Size()); i++ {
			out = append(out, byte(v>>(8*i)))
		}
	case *prog.GroupArg:
		for _, inner := range x.Inner {
			out = append(out, serialize(inner)...)
		}
	case *prog.UnionArg:
		out = append(out, serialize(x.Option)...)
	case *prog.DataArg:
		out = append(out, x.Data()...)
	}
	return out
}
